### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [hsnyder/FMacro#2]
I suggest adding the topics `preprocessor`, `generic-programming` in the About section.

Thanks for your project. I added it to my lists of Fortran [codes](https://github.com/Beliavsky/Fortran-code-on-GitHub) and [tools](https://github.com/Beliavsky/Fortran-Tools).

**Comment by hsnyder** [comment]
Thanks for the interest! I've done as you suggested.

**Comment by hsnyder** [comment]
@Beliavsky I'm sorry for the inconvenience, but I just renamed the project "FMacro", which may break your links.

**Comment by Beliavsky** [comment]
Fixed. New name is better IMO.
