### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by Beliavsky** [hsnyder/FMacro#3]
You write that FMacro is  "modeled after some of the language committee's early ideas for a template language feature." Is there a document you could link to? I would like to read it, although I understand that further generic features being officially included is a long way off.

**Comment by hsnyder** [comment]
Perhaps I stated that too strongly. All I really meant was that I worked in consultation with a member of the generics subcommittee when I was designing the syntax (I'm not part of that subcommittee myself). Damian (@rouson) might know if there's a publicly available document that demonstrates a line of thinking that resembles what we've done in FMacro. I'll inquire.

**Comment by hsnyder** [comment]
Here are some references that elucidate where the subgroup is currently at. 

Use cases for generics: https://j3-fortran.org/doc/year/21/21-144r4.txt

Proposed requirements for generics in Fortran: https://j3-fortran.org/doc/year/22/22-120r4.txt

Proposed specification for generics in Fortran: https://j3-fortran.org/doc/year/22/22-124r2.txt

Only the use cases paper can be considered final. The requirements and specification papers have not yet been approved.

**Comment by rouson** [comment]
At today's committee meeting, the committee voted to pass the requirements paper with revisions to come reflecting the impacts of "no" votes on each of the first three straw votes listed at the end of the paper, which in turn obviated the need for the fourth listed straw vote.  Once those promised revisions have been made, the requirements paper will be considered final.  There was some discussion of the specification paper and it appears that one will need more work so hopefully there will be a vote on that one at the upcoming July meeting.  If the specs paper passes, which might take one or two meetings, then I think we will have the green light to start working on syntax and semantics so I'm hoping that the templates feature for Fortran 202Y (the standard after next) will really begin to take shape late this year or early next year.  It's a lot of work with a lot of thorny issues and competing interests/opinions when attempting to add something this significant to a language of Medicare age!

**Comment by Beliavsky** [comment]
Thanks for the update @rouson . Would you mind if I quoted you on Fortran Discourse? I think your post deserves a larger audience than us three.

**Comment by rouson** [comment]
@Beliavsky it's probably best to quote me just up to the the sentence that ends in "July meeting."  What comes thereafter is speculative. I'm always one to try to inject humor, so the final sentence has is fair game too if you'd like to include it :)
